---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - kubernetes.core

  tasks:
    - debug:
        msg: "Debuging {{namespace}}"

    - name: delete the eclipse.org/v1.Amlen
      k8s:
        state: absent
        namespace: '{{ namespace }}'
        definition: "{{ lookup('template', '/'.join([samples_dir, cr_file])) | from_yaml }}"
      vars:
        cr_file: '_v1_amlen.yaml'


    - name: Wait for resources to get to absent
      k8s:
        namespace: '{{ namespace }}'
        definition: "{{ lookup('template', '/'.join([samples_dir, cr_file])) | from_yaml }}"
        state: absent
        wait: yes
      vars:
        cr_file: '_v1_amlen.yaml'

    - import_tasks: kustomize.yml
      vars:
        state: absent


    - name: Destroy Namespace
      k8s:
        api_version: v1
        kind: Namespace
        name: '{{ namespace }}'
        state: absent

    - name: Unset pull policy
      command: '{{ kustomize }} edit remove patch pull_policy/{{ operator_pull_policy }}.yaml'
      args:
        chdir: '{{ config_dir }}/testing'
