---
# defaults file for amlen
_amlen_namespace: amlen
_amlen_name: amlen
_amlen_release: amlen

_amlen_volume_size: 10Gi
_amlen_memory_request: 3Gi
_amlen_memory_limit: 3Gi
_amlen_cpu_request: 200m
_amlen_cpu_limit: 500m
_amlen_wait_for_init: true
_amlen_image: quay.io/amlen/amlen-server
_amlen_image_tag: IMG_TAG
_ldap_volume_size: 1Gi
_amlen_storage_class: default
_amlen_persistence: "true"
_amlen_topology_spread_constraints_when_unsatisfiable: ScheduleAnyway
_amlen_directory: "/var/lib/amlen-server/"
_amlen_bin_directory: "/usr/share/amlen-server/bin"

client_service_type: "ClusterIP"

amlen_messaging_ports:
  securemessaging: 8883

amlen_service_ports:
  admin: 9089

amlen_ha_ports:
  discovery: 9084
  replication: 9085
