---
# defaults file for amlen
#_amlen_state: present
_amlen_namespace: amlen
_amlen_name: amlen

_amlen_volume_size: 10Gi
_amlen_memory_request: 3Gi
_amlen_memory_limit: 3Gi
_amlen_cpu_request: 200m
_amlen_cpu_limit: 500m
_amlen_wait_for_init: true
_amlen_image: quay.io/amlen/amlen-server
_amlen_image_tag: IMG_TAG
_ldap_volume_size: 1Gi
_amlen_monitor_image: quay.io/amlen/amlen-monitor
_amlen_monitor_image_tag: IMG_TAG
_amlen_storage_class: default
_amlen_persistence: "true"

amlen_messaging_ports:
  securemessaging: 8883

amlen_service_ports:
  admin: 9089

amlen_ha_ports:
  discovery: 9084
  replication: 9085
