# Copyright (c) 2015-2021 Contributors to the Eclipse Foundation
# 
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
# 
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
# 
# SPDX-License-Identifier: EPL-2.0
#
include /etc/openldap/schema/core.schema
include /etc/openldap/schema/cosine.schema
include /etc/openldap/schema/inetorgperson.schema

loglevel 0
pidfile ${IMA_WEBUI_INSTALL_PATH}/openldap/config/slapd.pid
argsfile ${IMA_WEBUI_INSTALL_PATH}/openldap/config/slapd.args

# specifies the maximum number of entries to return from a search operation
sizelimit 500

# specifies the maximum number of seconds (in real time) slapd will spend
# answering a search request. If a request is not finished in this time,
# a result indicating an exceeded timelimit will be returned.
timelimit 3600


#######################################################################
# BDB database definitions
#######################################################################
database bdb
suffix "dc=ism.ibm,dc=com"
rootdn "cn=Directory Manager,dc=ism.ibm,dc=com"
rootpw secret
directory ${IMA_WEBUI_DATA_PATH}/openldap-data


# Indices to maintain
index objectClass eq

# specifies the number of entries that the LDAP backend will maintain in memory.
cachesize 10000

# check point whenever 1k data bytes written or
# 15 minutes has elapsed whichever occurs first
checkpoint 1 15

# specifies that the database does NOT need to be updated immediately with any in-memory records.
dbnosync

# Auto remove old transaction log files
dbconfig set_flags DB_LOG_AUTOREMOVE

