apiVersion: eclipse.org/v1
kind: Amlen
metadata:
  name: testsample-ue
spec:
  size: 1
  ha:
    cert_issuer:
      name: "amlen-selfsigned-issuer"
    enabled: true
  _amlen_namespace: "osdk-test"
  _amlen_name: "sample"
  _amlen_persistence: "false"
  client_service_type: "None"
  device_cert_issuer:
    mode: "automatic"
    name: "amlen-selfsigned-issuer"
  config: "amlen-config"
