apiVersion: eclipse.org/v1
kind: Amlen
metadata:
  name: testsample
spec:
  size: 2
  ha:
    cert_issuer:
      name: "amlen-selfsigned-issuer"
    enabled: true
  _amlen_namespace: "osdk-test"
  _amlen_name: "sample"
  _amlen_persistence: "false"
  device_cert_issuer:
    mode: "automatic"
    name: "amlen-selfsigned-issuer"
  config: "amlen-config"
  client_service_type: "LoadBalancer"
  amlen_messaging_ports:
    securemessaging:
      internal: 8883
      external: 443
