# permissions for end users to edit amlens.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: amlen-editor-role
rules:
- apiGroups:
  - eclipse.org
  resources:
  - amlens
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - eclipse.org
  resources:
  - amlens/status
  verbs:
  - get
