apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: amlen.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: operator for Amlen MQTT Broker
  displayName: amlen-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - amlen
  - mqtt
  - broker
  links:
  - name: Amlen
    url: https://amlen.domain
  maintainers:
  - email: ianboden@uk.ibm.com
    name: Ian Boden
  maturity: alpha
  provider:
    name: Ian
  version: 0.0.0
