apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: eclipse-amlen-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: Operator for the eclipse Amlen MQTT Broker\n\n### Supported Feature\n\n
    Currently supports:\n* Install - simple install process\n* Upgrade - non-disruptive upgrade\n*High
    Availability - can be enabled/disabled via the CRD\n\n### Documentation\nThe main
    Amlen website has links to product documentation, forum, blog and the slack channel\nhttp://www.eclipse.org/amlen\n\n###
    Getting help\nThe quickest way to get help is to use the slack channel but the
    forum is monitored as well\n\nIssues can also be added to the github repository
    https://github.com/eclipse/amlen\n\n### License\nEclipse Amlen Operator is licensed
    under the [Eclipse Public License - v 2.0](https://www.eclipse.org/legal/epl-2.0/)
  displayName: eclipse-amlen-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - amlen
  - mqtt
  - broker
  links:
  - name: Eclipse Amlen Operator
    url: https://eclipse-amlen-operator.domain
  maintainers:
  - email: ianboden@uk.ibm.com
    name: Ian Boden
  maturity: stable
  provider:
    name: Ian Boden
  version: 0.0.0
