apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: osdk-playop1.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: Jon playing around with Operator tutorials
  displayName: osdk-playop1
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - sample
  - play
  - test
  - tutorial
  links:
  - name: Osdk Playop1
    url: https://osdk-playop1.domain
  maintainers:
  - email: Not@my.email
    name: Jon
  maturity: alpha
  provider:
    name: Jon from Amlen team
  version: 0.0.0
