apiVersion: eclipse.org/v1alpha1
kind: Amlen
metadata:
  name: amlen-sample
spec:
  size: 2
  ha:
    cert_issuer:
      name: "amlen-selfsigned-issuer"
    enabled: true
  _amlen_namespace: "osdk-test"
  device_cert_issuer:
    mode: "automatic"
    name: "amlen-selfsigned-issuer"
  config: "amlen-config"
