apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "ca-internal"
  namespace: "cert-manager"
spec:
  secretName: "ca-internal"
  isCA: true
  duration: 175200h0m0s
  renewBefore: 2160h0m0s
  issuerRef:
    name: "amlen-selfsigned-issuer"
    kind: ClusterIssuer
  commonName: amlen-internal
