---
collections:
  - name: community.kubernetes
    version: "1.2.1"
  - name: operator_sdk.util
    version: "0.4.0"
  - name: kubernetes.core
  - name: cloud.common
    version: "2.1.0"
  - community.general
  - community.okd
